name: safe_crowd
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9.0
  - click=8.1.8
  - pyyaml6.0.2
  - numpy=1.20.3
  - casadi=3.6.7
  - scipy =1.10.1
  - matplotlib =3.6.2 
