dt: 0.1
init_type: default
mapsize:
- -6
- 6
- -6
- 6
obstacles:
- behavior:
    factor: 5.5
    mode: sfm
    type: all_obj
  color: k
  distribution:
    mode: x_left_right
    name: random
    range_high:
    - 5.6
    - 6
    - 3.14
    range_low:
    - -5.6
    - -6
    - -3.14
  kinematics: int
  noise:
  - - 0.01
    - 0.01
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
  number: 20
  radius: 0.4
  u_max:
  - 0.6
  - 0.6
  u_min:
  - 0.6
  - 0.6
random_seed: 23
robots:
- noise:
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
  radius: 0.3308387399584961
  target:
  - -6
  - 0
  - 0.001
  - 0
  type: doubleint
  x0:
  - 6
  - 0
  - 0
  - 0
